version: '3.8'

services:
  progress-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: progress-service:${IMAGE_TAG:-latest}
    container_name: progress-service-app-prod
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - API_PREFIX=${API_PREFIX:-api/v1}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
